In [3]:
import os
from PIL import Image
import numpy as np
from tensorflow.keras.models import load_model

In [4]:
def load_data(dataset_dir):
    images = []
    labels = []
    classes = sorted(os.listdir(dataset_dir))

    for i, class_name in enumerate(classes):
        class_dir = os.path.join(dataset_dir, class_name)
        for image_file in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_file)
            try:
                # Load image
                image = Image.open(image_path)
                # Convert image to numpy array or do any preprocessing
                # image = np.array(image)
                
                # Append image to the list
                images.append(image)
                
                # Append label to the list
                labels.append(class_name)
            except Exception as e:
                print(f"Error loading image: {image_path}. Error: {e}")

    return images, labels

In [5]:
# Function to load the trained model
def load_trained_model(model_path):
    model = load_model(model_path)  # Load the model from .h5 file
    return model

# Assuming you have a dataset directory named 'test_dataset' containing subdirectories for each class
dataset_dir = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/pretrained_testf'

# Load test data (features) and corresponding true labels
test_images, y_true = load_data(dataset_dir)

# Load your trained model
model_path = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/DenseNet169.h5'  # Path to your saved model
model = load_trained_model(model_path)

In [6]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.densenet import preprocess_input

def predict_labels(model, images):
    # Preprocess images according to DenseNet requirements
    processed_images = []
    for img in images:
        # Resize image to target input dimensions expected by DenseNet (e.g., 224x224 for DenseNet121)
        img = img.resize((256, 256))  # Adjust size as per your DenseNet model
        
        # Convert image to array and apply preprocessing required by DenseNet
        img_array = image.img_to_array(img)
        img_array = preprocess_input(img_array)
        
        processed_images.append(img_array)

    # Convert processed images to numpy array
    processed_images = np.array(processed_images)

    # Make predictions using the model
    predictions = model.predict(processed_images)

    # Convert predictions to class labels
    predicted_labels = np.argmax(predictions, axis=1)
    
    return predicted_labels

# Assuming you have a pre-trained DenseNet model stored in the variable 'model'
# And 'test_images' contains the images you want to make predictions on
# 'test_images' is assumed to be a list of PIL Image objects

# Make predictions using your trained model
y_pred = predict_labels(model, test_images)

77/77 [==============================] - 365s 4s/step


In [25]:
y_pred

array([0, 0, 2, ..., 5, 5, 5], dtype=int64)

In [8]:
y_true

['early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_leaf_spot_1',
 'early_le

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define class names
class_names = ["early_leaf_spot_1", "early_rust_1", "healthy_leaf_1", "late_leaf_spot_1", "nutrition_deficiency_1", "rust_1"]  # Replace with your actual class names

# Map numerical predictions to class names
y_pred_mapped = [class_names[prediction] for prediction in y_pred]

# Calculate accuracy
accuracy = accuracy_score(y_true, y_pred_mapped)

# Create a confusion matrix using the actual class names
cm = confusion_matrix(y_true, y_pred_mapped, labels=class_names)

# Generate a classification report using the actual class names
report = classification_report(y_true, y_pred_mapped, target_names=class_names)

print("Accuracy: {:.2f}".format(accuracy))
print("\nConfusion Matrix:")
print(cm)
print("\nClassification Report:")
print(report)

Accuracy: 0.87

Confusion Matrix:
[[357   0  11  41   0   0]
 [  0 403   0   6   0   0]
 [ 86   0 295  27   1   0]
 [  7   0   0 398   0   0]
 [  0   0   5   1 404   0]
 [  0  27   0 114   0 268]]

Classification Report:
                        precision    recall  f1-score   support

     early_leaf_spot_1       0.79      0.87      0.83       409
          early_rust_1       0.94      0.99      0.96       409
        healthy_leaf_1       0.95      0.72      0.82       409
      late_leaf_spot_1       0.68      0.98      0.80       405
nutrition_deficiency_1       1.00      0.99      0.99       410
                rust_1       1.00      0.66      0.79       409

              accuracy                           0.87      2451
             macro avg       0.89      0.87      0.87      2451
          weighted avg       0.89      0.87      0.87      2451



In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define class names
class_names = ["early_leaf_spot_1", "early_rust_1", "healthy_leaf_1", "late_leaf_spot_1", "nutrition_deficiency_1", "rust_1"]  # Replace with your actual class names

# Map numerical predictions to class names
y_pred_mapped = [class_names[prediction] for prediction in y_pred]

# Calculate accuracy
accuracy = accuracy_score(y_true, y_pred_mapped)

# Create a confusion matrix using the actual class names
cm = confusion_matrix(y_true, y_pred_mapped, labels=class_names)

# Generate a classification report using the actual class names
report = classification_report(y_true, y_pred_mapped, target_names=class_names)

print("Accuracy: {:.2f}".format(accuracy))
print("\nConfusion Matrix:")
print(cm)
print("\nClassification Report:")
print(report)


Accuracy: 0.87

Confusion Matrix:
[[357   0  11  41   0   0]
 [  0 403   0   6   0   0]
 [ 86   0 295  27   1   0]
 [  7   0   0 398   0   0]
 [  0   0   5   1 404   0]
 [  0  27   0 114   0 268]]

Classification Report:
                        precision    recall  f1-score   support

     early_leaf_spot_1       0.79      0.87      0.83       409
          early_rust_1       0.94      0.99      0.96       409
        healthy_leaf_1       0.95      0.72      0.82       409
      late_leaf_spot_1       0.68      0.98      0.80       405
nutrition_deficiency_1       1.00      0.99      0.99       410
                rust_1       1.00      0.66      0.79       409

              accuracy                           0.87      2451
             macro avg       0.89      0.87      0.87      2451
          weighted avg       0.89      0.87      0.87      2451



In [15]:
def load_data(dataset_dir):
    images = []
    labels = []
    classes = sorted(os.listdir(dataset_dir))

    for i, class_name in enumerate(classes):
        class_dir = os.path.join(dataset_dir, class_name)
        for image_file in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_file)
            try:
                # Load image
                image = Image.open(image_path)
                # Convert image to numpy array or do any preprocessing
                # image = np.array(image)
                
                # Append image to the list
                images.append(image)
                
                # Append label to the list
                labels.append(class_name)
            except Exception as e:
                print(f"Error loading image: {image_path}. Error: {e}")

    return images, labels

In [16]:
# Function to load the trained model
def load_trained_model(model_path):
    model = load_model(model_path)  # Load the model from .h5 file
    return model

# Assuming you have a dataset directory named 'test_dataset' containing subdirectories for each class
dataset_dir = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/pretrained_testf'

# Load test data (features) and corresponding true labels
test_images, y_true = load_data(dataset_dir)

# Load your trained model
model_path = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/Inceptionv3.h5'  # Path to your saved model
model = load_trained_model(model_path)

In [17]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.densenet import preprocess_input

def predict_labels(model, images):
    # Preprocess images according to DenseNet requirements
    processed_images = []
    for img in images:
        # Resize image to target input dimensions expected by DenseNet (e.g., 224x224 for DenseNet121)
        img = img.resize((256, 256))  # Adjust size as per your DenseNet model
        
        # Convert image to array and apply preprocessing required by DenseNet
        img_array = image.img_to_array(img)
        img_array = preprocess_input(img_array)
        
        processed_images.append(img_array)

    # Convert processed images to numpy array
    processed_images = np.array(processed_images)

    # Make predictions using the model
    predictions = model.predict(processed_images)

    # Convert predictions to class labels
    predicted_labels = np.argmax(predictions, axis=1)
    
    return predicted_labels

# Assuming you have a pre-trained DenseNet model stored in the variable 'model'
# And 'test_images' contains the images you want to make predictions on
# 'test_images' is assumed to be a list of PIL Image objects

# Make predictions using your trained model
y_pred = predict_labels(model, test_images)

77/77 [==============================] - 271s 2s/step


In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define class names
class_names = ["early_leaf_spot_1", "early_rust_1", "healthy_leaf_1", "late_leaf_spot_1", "nutrition_deficiency_1", "rust_1"]  # Replace with your actual class names

# Map numerical predictions to class names
y_pred_mapped = [class_names[prediction] for prediction in y_pred]

# Calculate accuracy
accuracy = accuracy_score(y_true, y_pred_mapped)

# Create a confusion matrix using the actual class names
cm = confusion_matrix(y_true, y_pred_mapped, labels=class_names)

# Generate a classification report using the actual class names
report = classification_report(y_true, y_pred_mapped, target_names=class_names)

print("Accuracy: {:.2f}".format(accuracy))
print("\nConfusion Matrix:")
print(cm)
print("\nClassification Report:")
print(report)


Accuracy: 0.81

Confusion Matrix:
[[312   0  71  13  13   0]
 [  1 305   0  22   0  81]
 [  1   0 360   0  48   0]
 [  5   0   0 400   0   0]
 [  1  51  24   3 330   1]
 [  1  26   0 106   6 270]]

Classification Report:
                        precision    recall  f1-score   support

     early_leaf_spot_1       0.97      0.76      0.85       409
          early_rust_1       0.80      0.75      0.77       409
        healthy_leaf_1       0.79      0.88      0.83       409
      late_leaf_spot_1       0.74      0.99      0.84       405
nutrition_deficiency_1       0.83      0.80      0.82       410
                rust_1       0.77      0.66      0.71       409

              accuracy                           0.81      2451
             macro avg       0.82      0.81      0.80      2451
          weighted avg       0.82      0.81      0.80      2451



In [19]:
def load_data(dataset_dir):
    images = []
    labels = []
    classes = sorted(os.listdir(dataset_dir))

    for i, class_name in enumerate(classes):
        class_dir = os.path.join(dataset_dir, class_name)
        for image_file in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_file)
            try:
                # Load image
                image = Image.open(image_path)
                # Convert image to numpy array or do any preprocessing
                # image = np.array(image)
                
                # Append image to the list
                images.append(image)
                
                # Append label to the list
                labels.append(class_name)
            except Exception as e:
                print(f"Error loading image: {image_path}. Error: {e}")

    return images, labels

In [20]:
# Function to load the trained model
def load_trained_model(model_path):
    model = load_model(model_path)  # Load the model from .h5 file
    return model

# Assuming you have a dataset directory named 'test_dataset' containing subdirectories for each class
dataset_dir = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/pretrained_testf'

# Load test data (features) and corresponding true labels
test_images, y_true = load_data(dataset_dir)

# Load your trained model
model_path = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/Xception.h5'  # Path to your saved model
model = load_trained_model(model_path)

In [21]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.densenet import preprocess_input

def predict_labels(model, images):
    # Preprocess images according to DenseNet requirements
    processed_images = []
    for img in images:
        # Resize image to target input dimensions expected by DenseNet (e.g., 224x224 for DenseNet121)
        img = img.resize((256, 256))  # Adjust size as per your DenseNet model
        
        # Convert image to array and apply preprocessing required by DenseNet
        img_array = image.img_to_array(img)
        img_array = preprocess_input(img_array)
        
        processed_images.append(img_array)

    # Convert processed images to numpy array
    processed_images = np.array(processed_images)

    # Make predictions using the model
    predictions = model.predict(processed_images)

    # Convert predictions to class labels
    predicted_labels = np.argmax(predictions, axis=1)
    
    return predicted_labels

# Assuming you have a pre-trained DenseNet model stored in the variable 'model'
# And 'test_images' contains the images you want to make predictions on
# 'test_images' is assumed to be a list of PIL Image objects

# Make predictions using your trained model
y_pred = predict_labels(model, test_images)

77/77 [==============================] - 383s 4s/step


In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define class names
class_names = ["early_leaf_spot_1", "early_rust_1", "healthy_leaf_1", "late_leaf_spot_1", "nutrition_deficiency_1", "rust_1"]  # Replace with your actual class names

# Map numerical predictions to class names
y_pred_mapped = [class_names[prediction] for prediction in y_pred]

# Calculate accuracy
accuracy = accuracy_score(y_true, y_pred_mapped)

# Create a confusion matrix using the actual class names
cm = confusion_matrix(y_true, y_pred_mapped, labels=class_names)

# Generate a classification report using the actual class names
report = classification_report(y_true, y_pred_mapped, target_names=class_names)

print("Accuracy: {:.2f}".format(accuracy))
print("\nConfusion Matrix:")
print(cm)
print("\nClassification Report:")
print(report)


Accuracy: 0.86

Confusion Matrix:
[[285   0 106  12   6   0]
 [  0 405   2   2   0   0]
 [  0   0 407   0   2   0]
 [ 39   0   0 366   0   0]
 [  0   2  19   0 389   0]
 [  0 142   0   4   2 261]]

Classification Report:
                        precision    recall  f1-score   support

     early_leaf_spot_1       0.88      0.70      0.78       409
          early_rust_1       0.74      0.99      0.85       409
        healthy_leaf_1       0.76      1.00      0.86       409
      late_leaf_spot_1       0.95      0.90      0.93       405
nutrition_deficiency_1       0.97      0.95      0.96       410
                rust_1       1.00      0.64      0.78       409

              accuracy                           0.86      2451
             macro avg       0.88      0.86      0.86      2451
          weighted avg       0.88      0.86      0.86      2451



In [26]:
# Function to load the trained model
def load_trained_model(model_path):
    model = load_model(model_path)  # Load the model from .h5 file
    return model

# Assuming you have a dataset directory named 'test_dataset' containing subdirectories for each class
dataset_dir = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/pretrained_testf'

# Load test data (features) and corresponding true labels
test_images, y_true = load_data(dataset_dir)

# Load your trained model
model_path = r'Documents/Groundnut_Leaf_dataset/Groundnut_Leaf_dataset/Xception.h5'  # Path to your saved model
model = load_trained_model(model_path)

In [28]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.densenet import preprocess_input

def predict_labels(model, images):
    # Preprocess images according to DenseNet requirements
    processed_images = []
    for img in images:
        # Resize image to target input dimensions expected by DenseNet (e.g., 224x224 for DenseNet121)
        img = img.resize((256, 256))  # Adjust size as per your DenseNet model
        
        # Convert image to array and apply preprocessing required by DenseNet
        img_array = image.img_to_array(img)
        img_array = preprocess_input(img_array)
        
        processed_images.append(img_array)

    # Convert processed images to numpy array
    processed_images = np.array(processed_images)

    # Make predictions using the model
    predictions = model.predict(processed_images)

    # Convert predictions to class labels
    predicted_labels = np.argmax(predictions, axis=1)
    
    return predicted_labels

# Assuming you have a pre-trained DenseNet model stored in the variable 'model'
# And 'test_images' contains the images you want to make predictions on
# 'test_images' is assumed to be a list of PIL Image objects

# Make predictions using your trained model
y_pred = predict_labels(model, test_images)

MemoryError: Unable to allocate 1.80 GiB for an array with shape (2451, 256, 256, 3) and data type float32